site_name: ADR-Wiki

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Light mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Dark mode


icon:
  favicon: assets/images/favicon.svg

extra_css:
  - stylesheets/extra.css
nav:
  - Главная: index.md
  - Инструкции:
      - instructions.md
      - Инструкция 1С УАТ для логистов Документ Заказ на ТС: zakaz na ts.md
  - Ресурсы: resources.md

